<?php

namespace App\Jobs\Fetches;

use App\Http\Controllers\RecipeController;
use App\Models\Items;
use App\Models\Recipes;
use App\Models\ResearchNotes;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class FetchResearchNotes implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $salvageableItemCategories = [
            ["Draconic", 5.5],
            ["Tempered Scale", 6],
            ["Barbaric", 5.5],
            ["Splint", 5],
            
            ["Superior Sigil", 1.1],
            ["Powerful Potion", 1.1],
            ["Potent Potion", 1.1],
            ["Strong Potion", 1.1],
            ["Minor Potion", 1.1],
            ["Pearl", 45],
            ["Bottle of Batwing Brew", 1],
            ["Tuning Crystal", 1],
            ["Green Wood Scepter", 1],
            ["Irradiated Focus", 1],
            ["Harpy Totem", 1],
            ["Tengu Echo", 50],
            ["Astral", 50],
            ["Peppermint Oil", 1.03],
            ["Restored Boreal", 40],
            ["Mordant", 45],
            ["Elder Wood Warhorn", 5.83],
            ["Quality Maintenance Oil", 1.1],
            ["Hard Wood Warhorn", 6],
            ["Seasoned Wood Warhorn", 5],
            ["Soft Wood Short Bow", 3.14],
            ["Journeyman Maintenance Oil", 1.04],
            ["Bronze Rifle", 1],
            ["Copper Stud", 1],
            ["The Twins'", 467],
            ["Emblazoned", 75],
            ["Lunatic Noble", 75],
            ["Prowler", 5],
            ["Noble", 5.36],
            ["Outlaw Mask", 3.2],
            ["Outlaw Shoulders", 3.2],
            ["Outlaw Coat", 3.2],
            ["Outlaw Gloves", 3.2],
            ["Outlaw Pants", 3.2],
            ["Outlaw Boots", 3.2],
            ["Seeker Shoulders", 1],
            ["Seeker Coat", 1],
            ["Seeker Gloves", 1],
            ["Seeker Pants", 1],
            ["Seeker Boots", 1],
            ["Jade Tech Masque", 75],
            ["Jade Tech Shoulderpads", 75],
            ["Jade Tech Vest", 75],
            ["Jade Tech Gloves", 75],
            ["Jade Tech Skirt", 75],
            ["Jade Tech Boots", 75],
            ["Exalted Masque", 75],
            ["Exalted Mantle", 75],
            ["Exalted Coat", 75],
            ["Exalted Gloves", 75],
            ["Exalted Pants", 75],
            ["Exalted Boots", 75],
            ["Mathilde's", 250],
            ["Sharpening Skull", 1.12],
            ["Krait Slayer", 6],
            ["Krait Pilum", 5.12],
            ["Darksteel Dagger", 6.14],
            ["Darksteel Axe", 6.26],
            ["Beaded", 7],
            ["Dredge Spear", 4.98],
            ["Bronze Axe", 1],
            ["Bronze Sword", 1],
            ["Bronze Mace", 1],
            ["Bronze Spear", 1],
            ["Adventurer's Mantle", 6],
            
            // % LIKE % ITEMS
            
            ["Cup of", 1.3],
            ["Extended Potion of", 1.1],
            ["Feathered", 5.5],
            ["Filet of", 1],
            ["Major Sigil", 1.1],
            ["Major Rune", 1.1],
            ["Minor Potion of", 1.1],
            ["Plate of", 1.1],
            ["Pot of", 1.1],

            // JEWELER % LIKE %
            ["Copper Amulet", 1.1],
            ["Copper Ring", 1.1],
            ["Copper Earring", 1.1],
            ["Silver Amulet", 2.2],
            ["Silver Ring", 2.2],
            ["Silver Earring", 2.2],
            ["Gold Amulet", 3.3],
            ["Gold Ring", 3.3],
            ["Gold Earring", 3.3],
            ["Platinum Amulet", 3.7],
            ["Platinum Ring", 3.7],
            ["Platinum Earring", 3.7],
            ["Mithril Amulet", 5.15],
            ["Mithril Ring", 5.15],
            ["Mithril Earring", 5.15],
            ["Orichalcum Amulet", 77.2],
            ["Orichalcum Ring", 77.2],
            ["Orichalcum Earring", 77.2],

            // ASCENDED ARMOR
            ["Ahamid's Visor", 500],
            ["Ahamid's Pauldrons", 500],
            ["Ahamid's Breastplate", 300],
            ["Ahamid's Warfists", 500],
            ["Ahamid's Tassets", 500],
            ["Ahamid's Greaves", 500],
            ["Ahamid's Visage", 500],
            ["Ahamid's Shoulderguard", 500],
            ["Ahamid's Doublet", 300],
            ["Ahamid's Grips", 500],
            ["Ahamid's Leggings", 500],
            ["Ahamid's Striders", 500],
            ["Ahamid's Masque", 500],
            ["Ahamid's Epaulets", 500],
            ["Ahamid's Doublet", 300],
            ["Ahamid's Wristguards", 500],
            ["Ahamid's Breeches", 500],
            ["Ahamid's Footwear", 500],
            ["Angchu Helm", 500],
            ["Angchu Shoulders", 500],
            ["Angchu Chestplate", 300],
            ["Angchu Gauntlets", 500],
            ["Angchu Legguards", 500],
            ["Angchu Boots", 500],
            ["Angchu Visage", 500],
            ["Angchu Shoulderguard", 500],
            ["Angchu Doublet", 300],
            ["Angchu Grips", 500],
            ["Angchu Leggings", 500],
            ["Angchu Striders", 500],
            ["Angchu Masque", 500],
            ["Angchu Epaulets", 500],
            ["Angchu Doublet", 300],
            ["Angchu Wristguards", 500],
            ["Angchu Breeches", 500],
            ["Angchu Footwear", 500],
            ["Beigarth's Helm", 500],
            ["Beigarth's Shoulders", 500],
            ["Beigarth's Chestplate", 300],
            ["Beigarth's Gauntlets", 500],
            ["Beigarth's Legguards", 500],
            ["Beigarth's Boots", 500],
            ["Beigarth's Visage", 500],
            ["Beigarth's Shoulderguard", 500],
            ["Beigarth's Doublet", 300],
            ["Beigarth's Grips", 500],
            ["Beigarth's Leggings", 500],
            ["Beigarth's Striders", 500],
            ["Beigarth's Masque", 500],
            ["Beigarth's Epaulets", 500],
            ["Beigarth's Doublet", 300],
            ["Beigarth's Wristguards", 500],
            ["Beigarth's Breeches", 500],
            ["Beigarth's Footwear", 500],
            ["Ferratus's Helm", 500],
            ["Ferratus's Shoulders", 500],
            ["Ferratus's Chestplate", 300],
            ["Ferratus's Gauntlets", 500],
            ["Ferratus's Legguards", 500],
            ["Ferratus's Boots", 500],
            ["Ferratus's Visage", 500],
            ["Ferratus's Shoulderguard", 500],
            ["Ferratus's Doublet", 300],
            ["Ferratus's Grips", 500],
            ["Ferratus's Leggings", 500],
            ["Ferratus's Striders", 500],
            ["Ferratus's Masque", 500],
            ["Ferratus's Epaulets", 500],
            ["Ferratus's Doublet", 300],
            ["Ferratus's Wristguards", 500],
            ["Ferratus's Breeches", 500],
            ["Ferratus's Footwear", 500],
            ["Forgemaster's Helm", 500],
            ["Forgemaster's Shoulders", 500],
            ["Forgemaster's Chestplate", 300],
            ["Forgemaster's Gauntlets", 500],
            ["Forgemaster's Legguards", 500],
            ["Forgemaster's Boots", 500],
            ["Forgemaster's Visage", 500],
            ["Forgemaster's Shoulderguard", 500],
            ["Forgemaster's Doublet", 300],
            ["Forgemaster's Grips", 500],
            ["Forgemaster's Leggings", 500],
            ["Forgemaster's Striders", 500],
            ["Forgemaster's Masque", 500],
            ["Forgemaster's Epaulets", 500],
            ["Forgemaster's Doublet", 300],
            ["Forgemaster's Wristguards", 500],
            ["Forgemaster's Breeches", 500],
            ["Forgemaster's Footwear", 500],
            ["Giftbringer's Visor", 500],
            ["Giftbringer's Pauldrons", 500],
            ["Giftbringer's Breastplate", 300],
            ["Giftbringer's Warfist", 500],
            ["Giftbringer's Tassets", 500],
            ["Giftbringer's Greaves", 500],
            ["Giftbringer's Visage", 500],
            ["Giftbringer's Shoulderguard", 500],
            ["Giftbringer's Doublet", 300],
            ["Giftbringer's Grips", 500],
            ["Giftbringer's Leggings", 500],
            ["Giftbringer's Striders", 500],
            ["Giftbringer's Masque", 500],
            ["Giftbringer's Epaulets", 500],
            ["Giftbringer's Doublet", 300],
            ["Giftbringer's Wristguards", 500],
            ["Giftbringer's Breeches", 500],
            ["Giftbringer's Footwear", 500],
            ["Gobrech's Helm", 500],
            ["Gobrech's Shoulders", 500],
            ["Gobrech's Chestplate", 300],
            ["Gobrech's Gauntlets", 500],
            ["Gobrech's Legguards", 500],
            ["Gobrech's Boots", 500],
            ["Gobrech's Visage", 500],
            ["Gobrech's Shoulderguard", 500],
            ["Gobrech's Doublet", 300],
            ["Gobrech's Grips", 500],
            ["Gobrech's Leggings", 500],
            ["Gobrech's Striders", 500],
            ["Gobrech's Masque", 500],
            ["Gobrech's Epaulets", 500],
            ["Gobrech's Doublet", 300],
            ["Gobrech's Wristguards", 500],
            ["Gobrech's Breeches", 500],
            ["Gobrech's Footwear", 500],
            ["Hronk's Helm", 500],
            ["Hronk's Shoulders", 500],
            ["Hronk's Breastplate", 300],
            ["Hronk's Gauntlets", 500],
            ["Hronk's Legguards", 500],
            ["Hronk's Boots", 500],
            ["Hronk's Visage", 500],
            ["Hronk's Shoulderguard", 500],
            ["Hronk's Doublet", 300],
            ["Hronk's Grips", 500],
            ["Hronk's Leggings", 500],
            ["Hronk's Striders", 500],
            ["Hronk's Masque", 500],
            ["Hronk's Epaulets", 500],
            ["Hronk's Doublet", 300],
            ["Hronk's Wristguards", 500],
            ["Hronk's Breeches", 500],
            ["Hronk's Footwear", 500],
            ["Laranthir's Visor", 500],
            ["Laranthir's Pauldrons", 500],
            ["Laranthir's Breastplate", 300],
            ["Laranthir's Warfist", 500],
            ["Laranthir's Tassets", 500],
            ["Laranthir's Greaves", 500],
            ["Laranthir's Visage", 500],
            ["Laranthir's Shoulderguard", 500],
            ["Laranthir's Doublet", 300],
            ["Laranthir's Grips", 500],
            ["Laranthir's Leggings", 500],
            ["Laranthir's Striders", 500],
            ["Laranthir's Masque", 500],
            ["Laranthir's Epaulets", 500],
            ["Laranthir's Doublet", 300],
            ["Laranthir's Wristguards", 500],
            ["Laranthir's Breeches", 500],
            ["Laranthir's Footwear", 500],
            ["Leftpaw's Helm", 500],
            ["Leftpaw's Shoulders", 500],
            ["Leftpaw's Chestplate", 300],
            ["Leftpaw's Gauntlets", 500],
            ["Leftpaw's Legguards", 500],
            ["Leftpaw's Boots", 500],
            ["Leftpaw's Visage", 500],
            ["Leftpaw's Shoulderguard", 500],
            ["Leftpaw's Doublet", 300],
            ["Leftpaw's Grips", 500],
            ["Leftpaw's Leggings", 500],
            ["Leftpaw's Striders", 500],
            ["Leftpaw's Masque", 500],
            ["Leftpaw's Epaulets", 500],
            ["Leftpaw's Doublet", 300],
            ["Leftpaw's Wristguards", 500],
            ["Leftpaw's Breeches", 500],
            ["Leftpaw's Footwear", 500],
            ["Maklain's Visor", 500],
            ["Maklain's Pauldrons", 500],
            ["Maklain's Breastplate", 300],
            ["Maklain's Warfist", 500],
            ["Maklain's Tassets", 500],
            ["Maklain's Greaves", 500],
            ["Maklain's Visage", 500],
            ["Maklain's Shoulderguard", 500],
            ["Maklain's Doublet", 300],
            ["Maklain's Grips", 500],
            ["Maklain's Leggings", 500],
            ["Maklain's Striders", 500],
            ["Maklain's Masque", 500],
            ["Maklain's Epaulets", 500],
            ["Maklain's Doublet", 300],
            ["Maklain's Wristguards", 500],
            ["Maklain's Breeches", 500],
            ["Maklain's Footwear", 500],
            ["Morbach's Helm", 500],
            ["Morbach's Shoulders", 500],
            ["Morbach's Chestplate", 300],
            ["Morbach's Gauntlets", 500],
            ["Morbach's Legguards", 500],
            ["Morbach's Boots", 500],
            ["Morbach's Visage", 500],
            ["Morbach's Shoulderguard", 500],
            ["Morbach's Doublet", 300],
            ["Morbach's Grips", 500],
            ["Morbach's Leggings", 500],
            ["Morbach's Striders", 500],
            ["Morbach's Masque", 500],
            ["Morbach's Epaulets", 500],
            ["Morbach's Doublet", 300],
            ["Morbach's Wristguards", 500],
            ["Morbach's Breeches", 500],
            ["Morbach's Footwear", 500],
            ["Nadijeh's Visor", 500],
            ["Nadijeh's Pauldrons", 500],
            ["Nadijeh's Breastplate", 300],
            ["Nadijeh's Warfist", 500],
            ["Nadijeh's Tassets", 500],
            ["Nadijeh's Greaves", 500],
            ["Nadijeh's Visage", 500],
            ["Nadijeh's Shoulderguard", 500],
            ["Nadijeh's Doublet", 300],
            ["Nadijeh's Grips", 500],
            ["Nadijeh's Leggings", 500],
            ["Nadijeh's Striders", 500],
            ["Nadijeh's Masque", 500],
            ["Nadijeh's Epaulets", 500],
            ["Nadijeh's Doublet", 300],
            ["Nadijeh's Wristguards", 500],
            ["Nadijeh's Breeches", 500],
            ["Nadijeh's Footwear", 500],
            ["Nerashi's Visor", 500],
            ["Nerashi's Pauldrons", 500],
            ["Nerashi's Breastplate", 300],
            ["Nerashi's Warfist", 500],
            ["Nerashi's Tassets", 500],
            ["Nerashi's Greaves", 500],
            ["Nerashi's Visage", 500],
            ["Nerashi's Shoulderguard", 500],
            ["Nerashi's Doublet", 300],
            ["Nerashi's Grips", 500],
            ["Nerashi's Leggings", 500],
            ["Nerashi's Striders", 500],
            ["Nerashi's Masque", 500],
            ["Nerashi's Epaulets", 500],
            ["Nerashi's Doublet", 300],
            ["Nerashi's Wristguards", 500],
            ["Nerashi's Breeches", 500],
            ["Nerashi's Footwear", 500],
            ["Occam's Helm", 500],
            ["Occam's Shoulders", 500],
            ["Occam's Chestplate", 300],
            ["Occam's Gauntlets", 500],
            ["Occam's Legguards", 500],
            ["Occam's Boots", 500],
            ["Occam's Visage", 500],
            ["Occam's Shoulderguard", 500],
            ["Occam's Doublet", 300],
            ["Occam's Grips", 500],
            ["Occam's Leggings", 500],
            ["Occam's Striders", 500],
            ["Occam's Masque", 500],
            ["Occam's Epaulets", 500],
            ["Occam's Doublet", 300],
            ["Occam's Wristguards", 500],
            ["Occam's Breeches", 500],
            ["Occam's Footwear", 500],
            ["Ossa's Visor", 500],
            ["Ossa's Pauldrons", 500],
            ["Ossa's Breastplate", 300],
            ["Ossa's Warfist", 500],
            ["Ossa's Tassets", 500],
            ["Ossa's Greaves", 500],
            ["Ossa's Visage", 500],
            ["Ossa's Shoulderguard", 500],
            ["Ossa's Doublet", 300],
            ["Ossa's Grips", 500],
            ["Ossa's Leggings", 500],
            ["Ossa's Striders", 500],
            ["Ossa's Masque", 500],
            ["Ossa's Epaulets", 500],
            ["Ossa's Doublet", 300],
            ["Ossa's Wristguards", 500],
            ["Ossa's Breeches", 500],
            ["Ossa's Footwear", 500],
            ["Pahua's Visor", 500],
            ["Pahua's Pauldrons", 500],
            ["Pahua's Breastplate", 300],
            ["Pahua's Warfist", 500],
            ["Pahua's Tassets", 500],
            ["Pahua's Greaves", 500],
            ["Pahua's Visage", 500],
            ["Pahua's Shoulderguard", 500],
            ["Pahua's Doublet", 300],
            ["Pahua's Grips", 500],
            ["Pahua's Leggings", 500],
            ["Pahua's Striders", 500],
            ["Pahua's Masque", 500],
            ["Pahua's Epaulets", 500],
            ["Pahua's Doublet", 300],
            ["Pahua's Wristguards", 500],
            ["Pahua's Breeches", 500],
            ["Pahua's Footwear", 500],
            ["Ruka's Visor", 500],
            ["Ruka's Pauldrons", 500],
            ["Ruka's Breastplate", 300],
            ["Ruka's Warfist", 500],
            ["Ruka's Tassets", 500],
            ["Ruka's Greaves", 500],
            ["Ruka's Visage", 500],
            ["Ruka's Shoulderguard", 500],
            ["Ruka's Doublet", 300],
            ["Ruka's Grips", 500],
            ["Ruka's Leggings", 500],
            ["Ruka's Striders", 500],
            ["Ruka's Masque", 500],
            ["Ruka's Epaulets", 500],
            ["Ruka's Doublet", 300],
            ["Ruka's Wristguards", 500],
            ["Ruka's Breeches", 500],
            ["Ruka's Footwear", 500],
            ["Saphir's Helm", 500],
            ["Saphir's Shoulders", 500],
            ["Saphir's Chestplate", 300],
            ["Saphir's Gauntlets", 500],
            ["Saphir's Legguards", 500],
            ["Saphir's Boots", 500],
            ["Saphir's Visage", 500],
            ["Saphir's Shoulderguard", 500],
            ["Saphir's Doublet", 300],
            ["Saphir's Grips", 500],
            ["Saphir's Leggings", 500],
            ["Saphir's Striders", 500],
            ["Saphir's Masque", 500],
            ["Saphir's Epaulets", 500],
            ["Saphir's Doublet", 300],
            ["Saphir's Wristguards", 500],
            ["Saphir's Breeches", 500],
            ["Saphir's Footwear", 500],
            ["Steelstar's Visor", 500],
            ["Steelstar's Pauldrons", 500],
            ["Steelstar's Breastplate", 300],
            ["Steelstar's Warfist", 500],
            ["Steelstar's Tassets", 500],
            ["Steelstar's Greaves", 500],
            ["Steelstar's Visage", 500],
            ["Steelstar's Shoulderguard", 500],
            ["Steelstar's Doublet", 300],
            ["Steelstar's Grips", 500],
            ["Steelstar's Leggings", 500],
            ["Steelstar's Striders", 500],
            ["Steelstar's Masque", 500],
            ["Steelstar's Epaulets", 500],
            ["Steelstar's Doublet", 300],
            ["Steelstar's Wristguards", 500],
            ["Steelstar's Breeches", 500],
            ["Steelstar's Footwear", 500],
            ["Suun's Visor", 500],
            ["Suun's Pauldrons", 500],
            ["Suun's Breastplate", 300],
            ["Suun's Warfist", 500],
            ["Suun's Tassets", 500],
            ["Suun's Greaves", 500],
            ["Suun's Visage", 500],
            ["Suun's Shoulderguard", 500],
            ["Suun's Doublet", 300],
            ["Suun's Grips", 500],
            ["Suun's Leggings", 500],
            ["Suun's Striders", 500],
            ["Suun's Masque", 500],
            ["Suun's Epaulets", 500],
            ["Suun's Doublet", 300],
            ["Suun's Wristguards", 500],
            ["Suun's Breeches", 500],
            ["Suun's Footwear", 500],
            ["Svaard's Visor", 500],
            ["Svaard's Pauldrons", 500],
            ["Svaard's Breastplate", 300],
            ["Svaard's Warfist", 500],
            ["Svaard's Tassets", 500],
            ["Svaard's Greaves", 500],
            ["Svaard's Visage", 500],
            ["Svaard's Shoulderguard", 500],
            ["Svaard's Doublet", 300],
            ["Svaard's Grips", 500],
            ["Svaard's Leggings", 500],
            ["Svaard's Striders", 500],
            ["Svaard's Masque", 500],
            ["Svaard's Epaulets", 500],
            ["Svaard's Doublet", 300],
            ["Svaard's Wristguards", 500],
            ["Svaard's Breeches", 500],
            ["Svaard's Footwear", 500],
            ["Tateos's Helm", 500],
            ["Tateos's Shoulders", 500],
            ["Tateos's Chestplate", 300],
            ["Tateos's Gauntlets", 500],
            ["Tateos's Legguards", 500],
            ["Tateos's Boots", 500],
            ["Tateos's Visage", 500],
            ["Tateos's Shoulderguard", 500],
            ["Tateos's Doublet", 300],
            ["Tateos's Grips", 500],
            ["Tateos's Leggings", 500],
            ["Tateos's Striders", 500],
            ["Tateos's Masque", 500],
            ["Tateos's Epaulets", 500],
            ["Tateos's Doublet", 300],
            ["Tateos's Wristguards", 500],
            ["Tateos's Breeches", 500],
            ["Tateos's Footwear", 500],
            ["Thackeray's Visor", 500],
            ["Thackeray's Pauldrons", 500],
            ["Thackeray's Breastplate", 300],
            ["Thackeray's Warfist", 500],
            ["Thackeray's Tassets", 500],
            ["Thackeray's Greaves", 500],
            ["Thackeray's Visage", 500],
            ["Thackeray's Shoulderguard", 500],
            ["Thackeray's Doublet", 300],
            ["Thackeray's Grips", 500],
            ["Thackeray's Leggings", 500],
            ["Thackeray's Striders", 500],
            ["Thackeray's Masque", 500],
            ["Thackeray's Epaulets", 500],
            ["Thackeray's Doublet", 300],
            ["Thackeray's Wristguards", 500],
            ["Thackeray's Breeches", 500],
            ["Thackeray's Footwear", 500],
            ["The Twins' Visor", 500],
            ["The Twins' Pauldrons", 500],
            ["The Twins' Breastplate", 300],
            ["The Twins' Warfist", 500],
            ["The Twins' Tassets", 500],
            ["The Twins' Greaves", 500],
            ["The Twins' Visage", 500],
            ["The Twins' Shoulderguard", 500],
            ["The Twins' Doublet", 300],
            ["The Twins' Grips", 500],
            ["The Twins' Leggings", 500],
            ["The Twins' Striders", 500],
            ["The Twins' Masque", 500],
            ["The Twins' Epaulets", 500],
            ["The Twins' Doublet", 300],
            ["The Twins' Wristguards", 500],
            ["The Twins' Breeches", 500],
            ["The Twins' Footwear", 500],
            ["Tixx's Visor", 500],
            ["Tixx's Pauldrons", 500],
            ["Tixx's Breastplate", 300],
            ["Tixx's Warfist", 500],
            ["Tixx's Tassets", 500],
            ["Tixx's Greaves", 500],
            ["Tixx's Visage", 500],
            ["Tixx's Shoulderguard", 500],
            ["Tixx's Doublet", 300],
            ["Tixx's Grips", 500],
            ["Tixx's Leggings", 500],
            ["Tixx's Striders", 500],
            ["Tixx's Masque", 500],
            ["Tixx's Epaulets", 500],
            ["Tixx's Doublet", 300],
            ["Tixx's Wristguards", 500],
            ["Tixx's Breeches", 500],
            ["Tixx's Footwear", 500],
            ["Tizlak's Visor", 500],
            ["Tizlak's Pauldrons", 500],
            ["Tizlak's Breastplate", 300],
            ["Tizlak's Warfist", 500],
            ["Tizlak's Tassets", 500],
            ["Tizlak's Greaves", 500],
            ["Tizlak's Visage", 500],
            ["Tizlak's Shoulderguard", 500],
            ["Tizlak's Doublet", 300],
            ["Tizlak's Grips", 500],
            ["Tizlak's Leggings", 500],
            ["Tizlak's Striders", 500],
            ["Tizlak's Masque", 500],
            ["Tizlak's Epaulets", 500],
            ["Tizlak's Doublet", 300],
            ["Tizlak's Wristguards", 500],
            ["Tizlak's Breeches", 500],
            ["Tizlak's Footwear", 500],
            ["Togo's Visor", 500],
            ["Togo's Pauldrons", 500],
            ["Togo's Breastplate", 300],
            ["Togo's Warfist", 500],
            ["Togo's Tassets", 500],
            ["Togo's Greaves", 500],
            ["Togo's Visage", 500],
            ["Togo's Shoulderguard", 500],
            ["Togo's Doublet", 300],
            ["Togo's Grips", 500],
            ["Togo's Leggings", 500],
            ["Togo's Striders", 500],
            ["Togo's Masque", 500],
            ["Togo's Epaulets", 500],
            ["Togo's Doublet", 300],
            ["Togo's Wristguards", 500],
            ["Togo's Breeches", 500],
            ["Togo's Footwear", 500],
            ["Veldrunner Helm", 500],
            ["Veldrunner Shoulders", 500],
            ["Veldrunner Brestplate", 300],
            ["Veldrunner Gauntlets", 500],
            ["Veldrunner Legguards", 500],
            ["Veldrunner Boots", 500],
            ["Veldrunner Visage", 500],
            ["Veldrunner Shoulderguard", 500],
            ["Veldrunner Doublet", 300],
            ["Veldrunner Grips", 500],
            ["Veldrunner Leggings", 500],
            ["Veldrunner Striders", 500],
            ["Veldrunner Masque", 500],
            ["Veldrunner Epaulets", 500],
            ["Veldrunner Doublet", 300],
            ["Veldrunner Wristguards", 500],
            ["Veldrunner Breeches", 500],
            ["Veldrunner Footwear", 500],
            ["Veldrunner Helm", 500],
            ["Ventari's Visor", 500],
            ["Ventari's Pauldrons", 500],
            ["Ventari's Breastplate", 300],
            ["Ventari's Warfist", 500],
            ["Ventari's Tassets", 500],
            ["Ventari's Greaves", 500],
            ["Ventari's Visage", 500],
            ["Ventari's Shoulderguard", 500],
            ["Ventari's Doublet", 300],
            ["Ventari's Grips", 500],
            ["Ventari's Leggings", 500],
            ["Ventari's Striders", 500],
            ["Ventari's Masque", 500],
            ["Ventari's Epaulets", 500],
            ["Ventari's Doublet", 300],
            ["Ventari's Wristguards", 500],
            ["Ventari's Breeches", 500],
            ["Ventari's Footwear", 500],
            ["Verata's Visor", 500],
            ["Verata's Pauldrons", 500],
            ["Verata's Breastplate", 300],
            ["Verata's Warfist", 500],
            ["Verata's Tassets", 500],
            ["Verata's Greaves", 500],
            ["Verata's Visage", 500],
            ["Verata's Shoulderguard", 500],
            ["Verata's Doublet", 300],
            ["Verata's Grips", 500],
            ["Verata's Leggings", 500],
            ["Verata's Striders", 500],
            ["Verata's Masque", 500],
            ["Verata's Epaulets", 500],
            ["Verata's Doublet", 300],
            ["Verata's Wristguards", 500],
            ["Verata's Breeches", 500],
            ["Verata's Footwear", 500],
            ["Wei Qi's Helm", 500],
            ["Wei Qi's Shoulders", 500],
            ["Wei Qi's Chestplate", 300],
            ["Wei Qi's Gauntlets", 500],
            ["Wei Qi's Legguards", 500],
            ["Wei Qi's Boots", 500],
            ["Wei Qi's Visage", 500],
            ["Wei Qi's Shoulderguard", 500],
            ["Wei Qi's Doublet", 300],
            ["Wei Qi's Grips", 500],
            ["Wei Qi's Leggings", 500],
            ["Wei Qi's Striders", 500],
            ["Wei Qi's Masque", 500],
            ["Wei Qi's Epaulets", 500],
            ["Wei Qi's Doublet", 300],
            ["Wei Qi's Wristguards", 500],
            ["Wei Qi's Breeches", 500],
            ["Wei Qi's Footwear", 500],
            ["Wupwup Helm", 500],
            ["Wupwup Shoulders", 500],
            ["Wupwup Chestplate", 300],
            ["Wupwup Gauntlets", 500],
            ["Wupwup Legguards", 500],
            ["Wupwup Boots", 500],
            ["Wupwup Visage", 500],
            ["Wupwup Shoulderguard", 500],
            ["Wupwup Doublet", 300],
            ["Wupwup Grips", 500],
            ["Wupwup Leggings", 500],
            ["Wupwup Striders", 500],
            ["Wupwup Masque", 500],
            ["Wupwup Epaulets", 500],
            ["Wupwup Doublet", 300],
            ["Wupwup Wristguards", 500],
            ["Wupwup Breeches", 500],
            ["Wupwup Footwear", 500],
            ["Yassith's Visor", 500],
            ["Yassith's Pauldrons", 500],
            ["Yassith's Breastplate", 300],
            ["Yassith's Warfist", 500],
            ["Yassith's Tassets", 500],
            ["Yassith's Greaves", 500],
            ["Yassith's Visage", 500],
            ["Yassith's Shoulderguard", 500],
            ["Yassith's Doublet", 300],
            ["Yassith's Grips", 500],
            ["Yassith's Leggings", 500],
            ["Yassith's Striders", 500],
            ["Yassith's Masque", 500],
            ["Yassith's Epaulets", 500],
            ["Yassith's Doublet", 300],
            ["Yassith's Wristguards", 500],
            ["Yassith's Breeches", 500],
            ["Yassith's Footwear", 500],
            ["Zehtuka's Visor", 500],
            ["Zehtuka's Pauldrons", 500],
            ["Zehtuka's Breastplate", 300],
            ["Zehtuka's Warfist", 500],
            ["Zehtuka's Tassets", 500],
            ["Zehtuka's Greaves", 500],
            ["Zehtuka's Visage", 500],
            ["Zehtuka's Shoulderguard", 500],
            ["Zehtuka's Doublet", 300],
            ["Zehtuka's Grips", 500],
            ["Zehtuka's Leggings", 500],
            ["Zehtuka's Striders", 500],
            ["Zehtuka's Masque", 500],
            ["Zehtuka's Epaulets", 500],
            ["Zehtuka's Doublet", 300],
            ["Zehtuka's Wristguards", 500],
            ["Zehtuka's Breeches", 500],
            ["Zehtuka's Footwear", 500],
            ["Zintl Helm", 500],
            ["Zintl Shoulders", 500],
            ["Zintl Chestplate", 300],
            ["Zintl Gauntlets", 500],
            ["Zintl Legguards", 500],
            ["Zintl Boots", 500],
            ["Zintl Visage", 500],
            ["Zintl Shoulderguard", 500],
            ["Zintl Doublet", 300],
            ["Zintl Grips", 500],
            ["Zintl Leggings", 500],
            ["Zintl Striders", 500],
            ["Zintl Masque", 500],
            ["Zintl Epaulets", 500],
            ["Zintl Doublet", 300],
            ["Zintl Wristguards", 500],
            ["Zintl Breeches", 500],
            ["Zintl Footwear", 500],
            ["Zojja's Helm", 500],
            ["Zojja's Shoulders", 500],
            ["Zojja's Chestplate", 300],
            ["Zojja's Gauntlets", 500],
            ["Zojja's Legguards", 500],
            ["Zojja's Boots", 500],
            ["Zojja's Visage", 500],
            ["Zojja's Shoulderguard", 500],
            ["Zojja's Doublet", 300],
            ["Zojja's Grips", 500],
            ["Zojja's Leggings", 500],
            ["Zojja's Striders", 500],
            ["Zojja's Masque", 500],
            ["Zojja's Epaulets", 500],
            ["Zojja's Doublet", 300],
            ["Zojja's Wristguards", 500],
            ["Zojja's Breeches", 500],
            ["Zojja's Footwear", 500],
            
            // OTHER ARMOR
            ["Amnemoi's Robe", 7.5],
            ["Anointed Diadem", 7.5],
            ["Barca's", 3.5],
            ["Bella's", 13],
            ["Blessed Steps", 11.5],
            ["Bloodsaw Leather", 3.7],
            ["Breezy Backplate", 11.5],
            ["Brightcarved", 5.6],
            ["Cabras", 3.5],
            ["Clarion", 7],
            ["Clark's Chukkas", 13],
            ["Cloven", 3.7],
            ["Cumulus Habit", 8],
            ["Darkvine", 1.1],
            ["Dashing Tricorner", 11.5],
            ["Dessicated Pauldrons", 3.5],
            ["Devout", 3.6],
            ["Dragon's Jade Tech", 75],
            ["Dual Peaks", 4.4],
            ["Duty-Bound", 1.1],
            ["Excavator's Gloves", 7],
            ["Gieve's", 11.5],
            ["Grieving Elegy", 6.4],
            ["Groaning", 6],
            ["Highsteppers", 6],
            ["Homespun", 3.7],
            ["Imuthi's", 11.5],
            ["Inconnu's", 7],
            ["Inconspicuous", 7],
            ["Iron Legion's", 1.1],
            ["Irresistiable", 11.5],
            ["Kid Gloves", 3.7],
            ["Mail of Mac", 11.5],
            ["Many-Buckled", 11.5],
            ["Mask of 1,000 Faces", 7],
            ["Massey's", 11.5],
            ["Miucha's", 11.5],
            ["Obfuscation", 7],
            ["Ostholz's", 3.5],
            ["Pike's Ambition", 7],
            ["Pious", 7],
            ["Quiet Leather", 7],
            ["Ragamuffin", 3.7],
            ["Rattling", 3.7],
            ["Sepulchre", 11.5],
            ["Shadow Garb", 3.7],
            ["Shadow Gloves", 3.7],
            ["Shadow Helm", 3.7],
            ["Shadow Leggings", 3.7],
            ["Shadow Mantle", 3.7],
            ["Shadow Shoes", 3.7],
            ["Stiletto", 11.5],
            ["Swelter's", 7],
            ["Trackless", 11.5],
            ["Witherbreeches", 3.7],

            // CHEF
            ["Artisan Maintenance Oil", 1.1],
            ["Artisan Tuning Crystal", 1.1],
            ["Block of Tofu", 1.1],
            ["Bottle of Batwing Brew", 1.1],
            ["Bountiful Maintenance Oil", 1.1],
            ["Bountiful Sharpening Stone", 1.1],
            ["Bowl of", 1.3],
            ["Candy Corn Cake", 1.1],
            ["Candy Corn Cookie", 1.1],
            ["Carrot Soufflé", 1.1],
            ["Cheeze Pizza", 1.1],
            ["Cheesy Cassava Roll", 1.1],
            ["Chef's Tasting Platter", 1.1],
            ["Cherry Pie", 1.1],
            ["Cherry Almost Bar", 1.1],
            ["Cherry Cookie", 1.1],
            ["Cherry Pie", 1.1],
            ["Cherry Tart", 1.1],
            ["Chickpea Fritter", 1.1],
            ["Chocolate Banana", 1.1],
            ["Chocolate Cake", 1.1],
            ["Chocolate Cherry", 1.1],
            ["Chocolate Cherry Cake", 1.1],
            ["Chocolate Chip Cookie", 1.1],
            ["Chocolate Mint Cookie", 1.1],
            ["Chocolate Omnomberry Cake", 1.1],
            ["Chocolate Omnomberry Cream", 1.1],
            ["Chocolate Orange", 1.1],
            ["Chocolate Raspberry Cake", 1.1],
            ["Chocolate Raspberry Cookie", 1.1],
            ["Chocolate Raspberry Cream", 1.1],
            ["Cilantro Lime Sous-Vide Steak", 1.1],
            ["Cilantro and Cured Meat Flatbread", 1.1],
            ["Clam Cake", 1.1],
            ["Clove-Spiced Creme Brulee", 1.1],
            ["Clove-Spiced Eggs Benedict", 1.1],
            ["Clove-Spiced Pear and Cured Meat Flatbread", 1.1],
            ["Clove and Veggie Flatbread", 1.1],
            ["Deluxe Burger", 1.1],
            ["Dilled Poultry Piccata", 1.1],
            ["Divinity Stuffed Mushroom", 1.1],
            ["Dragon's Revelry Starcake", 1.1],
            ["Eggplant Fritter", 1.1],
            ["Eggs Benedict with Mint-Parsley Sauce", 1.1],
            ["Enhanced Lucent Oil", 1.1],
            ["Eztlitl Stuffed Mushroom", 1.1],
            ["Fancy Truffle Burger", 1.1],
            ["Fancy Veggie Pizza", 1.1],
            ["Filet of Rosemary-Roasted Meat", 1.1],
            ["Filet of Sesame-Roasted Meat", 1.1],
            ["Fishy Rice Bowl", 1.1],
            ["Flask of Pumpkin Oil", 1.1],
            ["Flatbread", 1.1],
            ["Flight of Sushi", 1.1],
            ["Fried Oyster Sandwich", 1.1],
            ["Fried Oysters", 1.1],
            ["Furious Maintenance Oil", 1.1],
            ["Furious Sharpening Stone", 1.1],
            ["Furious Tuning Crystal", 1.1],
            ["Ghost Pepper Popper", 1.1],
            ["Giant Chocolate Cake", 1.1],
            ["Giant Chocolate Cherry Cake", 1.1],
            ["Giant Chocolate Omnomberry Cake", 1.1],
            ["Giant Chocolate Raspberry Cake", 1.1],
            ["Giant Orange Coconut Cake", 1.1],
            ["Ginger Pear Tart", 1.1],
            ["Glazed Chocolate Raspberry Cookie", 1.1],
            ["Glazed Peach Tart", 1.1],
            ["Glazed Pear Tart", 1.1],
            ["Glazed Pumpkin Pie", 1.1],
            ["Grape Pie", 1.1],
            ["Grawl Snowman Potion", 1.1],
            ["Griffon Egg Omelet", 1.1],
            ["Grilled Portobello Mushroom", 1.1],
            ["Guaranteed Blue-Green Dye Unlock", 1.1],
            ["Guaranteed Purple-Gray Dye Unlock", 1.1],
            ["Guaranteed Red-Brown Dye Unlock", 1.1],
            ["Guaranteed Yellow-Orange Dye Unlock", 1.1],
            ["Handful of Trail Mix", 1.1],
            ["Hardened Sharpening Stone", 1.1],
            ["Horseradish Burger", 1.1],
            ["Hylek Maintenance Oil", 1.1],
            ["Indigo Mushroom Milkshake", 1.1],
            ["Jerk Poultry Flatbread Sandwich", 1.1],
            ["Jerk Poultry and Nopal Flatbread Sandwich", 1.1],
            ["Journeyman Maintenance Oil", 1.1],
            ["Journeyman Tuning Crystal", 1.1],
            ["Kastaz Roasted Poultry", 1.1],
            ["Krait Tuning Crystal", 1.1],
            ["Lake Doric Mussels", 1.1],
            ["Lemon Bar", 1.1],
            ["Loaf of Candy Cactus Cornbread", 1.1],
            ["Loaf of Omnomberry Bread", 1.1],
            ["Loaf of Saffron Bread", 1.1],
            ["Loaf of Walnut Sticky Bread", 1.1],
            ["Lump of Crystallized Nougat", 1.1],
            ["Maintenance Oil Station", 1.1],
            ["Mango Cilantro Creme Brulee", 1.1],
            ["Mango Pie", 1.1],
            ["Master Maintenance Oil", 1.1],
            ["Master Tuning Crystal", 1.1],
            ["Meatball", 1.1],
            ["Meatball Dinner", 1.1],
            ["Meaty Asparagus Skewer", 1.1],
            ["Meaty Rice Bowl", 1.1],
            ["Minotaur Steak", 1.1],
            ["Mint-Pear Cured Meat Flatbread", 1.1],
            ["Mint Creme Brulee", 1.1],
            ["Mint Strawberry Cheesecake", 1.1],
            ["Mint and Veggie Flatbread", 1.1],
            ["Mixed Berry Pie", 1.1],
            ["Mushroom Clove Sous-Vide Steak", 1.1],
            ["Mushroom Loaf", 1.1],
            ["Mushroom Pizza", 1.1],
            ["Ogre Sharpening Stone", 1.1],
            ["Omnomberry Bar", 1.1],
            ["Omnomberry Cookie", 1.1],
            ["Omnomberry Ghost", 1.1],
            ["Omnomberry Pie", 1.1],
            ["Omnomberry Tart", 1.1],
            ["Orange Cake", 1.1],
            ["Orange Clove Cheesecake", 1.1],
            ["Orange Coconut Bar", 1.1],
            ["Orange Coconut Cake", 1.1],
            ["Orange Passion Fruit Tart", 1.1],
            ["Orangefish Sushi", 1.1],
            ["Oysters Gnashblade", 1.1],
            ["Oysters with Cocktail Sauce", 1.1],
            ["Oysters with Pesto Sauce", 1.1],
            ["Oysters with Spicy Sauce", 1.1],
            ["Oysters with Zesty Sauce", 1.1],
            ["Passion Fruit Bar", 1.1],
            ["Passion Fruit Coconut Cookie", 1.1],
            ["Peach Cookie", 1.1],
            ["Peach Pie", 1.1],
            ["Peach Tart", 1.1],
            ["Pepper Steak", 1.1],
            ["Pepper Steak Dinner", 1.1],
            ["Peppercorn-Crusted Sous-Vide Steak", 1.1],
            ["Peppercorn-Spiced Eggs Benedict", 1.1],
            ["Peppercorn and Veggie Flatbread", 1.1],
            ["Peppered Cured Meat Flatbread", 1.1],
            ["Peppermint Oil", 1.1],
            ["Peppermint Omnomberry Bar", 1.1],
            ["Piece of Candy Corn Almond Brittle", 1.1],
            ["Pitcher of Desert-Spiced Coffee", 1.1],
            ["Potent Lucent Oil", 1.1],
            ["Potent Master Maintenance Oil", 1.1],
            ["Potent Master Tuning Crystal", 1.1],
            ["Prickly Pear Pie", 1.1],
            ["Prickly Pear Stuffed Nopal", 1.1],
            ["Pumpkin Pie", 1.1],
            ["Quality Maintenance Oil", 1.1],
            ["Quality Sharpening Stone", 1.1],
            ["Quality Tuning Crystal", 1.1],
            ["Rare Veggie Pizza", 1.1],
            ["Raspberry Passion Fruit Compote", 1.1],
            ["Raspberry Peach Bar", 1.1],
            ["Raspberry Pie", 1.1],
            ["Red-Lentil Saobosa", 1.1],
            ["Red Lentil and Flatbread Feast", 1.1],
            ["Redfish Sushi", 1.1],
            ["Ring of Blood", 1.1],
            ["Roasted Artichoke", 1.1],
            ["Roasted Parsnip", 1.1],
            ["Roasted Rutabaga", 1.1],
            ["Saffron Mussels", 1.1],
            ["Saffron Stuffed Mushroom", 1.1],
            ["Sage-Stuffed Mushroom", 1.1],
            ["Sage-Stuffed Poultry", 1.1],
            ["Salsa-Topped Veggie Flatbread", 1.1],
            ["Salsa Eggs Benedict", 1.1],
            ["Scoop of Mintberry Swirl Ice Cream", 1.1],
            ["Sesame-Asparagus and Cured Meat Flatbread", 1.1],
            ["Sesame-Roasted Dinner", 1.1],
            ["Sesame Cheesecake", 1.1],
            ["Sesame Creme Brulee", 1.1],
            ["Sesame Eggs Benedict", 1.1],
            ["Sesame Veggie Flatbread", 1.1],
            ["Sharpening Skull", 1.1],
            ["Sharpening Stone Station", 1.1],
            ["Simple Sharpening Stone", 1.1],
            ["Slice of Allspice Cake", 1.1],
            ["Slice of Allspice Cake with Ice Cream", 1.1],
            ["Slice of Pumpkin Bread", 1.1],
            ["Sous-Vide Steak with Mint-Parsley Sauce", 1.1],
            ["Soy-Sesame Sous-Vide Steak", 1.1],
            ["Spherified Cilantro Oyster Soup", 1.1],
            ["Spherified Clove-Spiced Oyster Soup", 1.1],
            ["Spherified Oyster Soup with Mint Garnish", 1.1],
            ["Spherified Peppercorn-Spiced Oyster Soup", 1.1],
            ["Spherified Sesame Oyster Soup", 1.1],
            ["Spiced Pepper Creme Brulee", 1.1],
            ["Spiced Peppercorn Cheesecake", 1.1],
            ["Spicier Flank Steak", 1.1],
            ["Spicy Cheeseburger", 1.1],
            ["Spicy Chocolate Cookie", 1.1],
            ["Spicy Lime Steak", 1.1],
            ["Spicy Marinated Mushroom", 1.1],
            ["Spicy Pumpkin Cookie", 1.1],
            ["Spicy Stuffed Mushroom", 1.1],
            ["Spinach Burger", 1.1],
            ["Spinach Salad", 1.1],
            ["Standard Maintenance Oil", 1.1],
            ["Standard Sharpening Stone", 1.1],
            ["Standard Tuning Crystal", 1.1],
            ["Stargazer Pendant", 1.1],
            ["Steak with Winterberry Sauce", 1.1],
            ["Strawberries and Biscuits", 1.1],
            ["Strawberry Cilantro Cheesecake", 1.1],
            ["Strawberry Cookie", 1.1],
            ["Strawberry Ghost", 1.1],
            ["Strawberry Pie", 1.1],
            ["Strawberry Tart", 1.1],
            ["Stuffed Artichoke with Tropical Dressing", 1.1],
            ["Stuffed Pepper", 1.1],
            ["Stuffed Zucchini", 1.1],
            ["Super Mixed Parfait", 1.1],
            ["Super Veggie Pizza", 1.1],
            ["Tarragon Stuffed Poultry", 1.1],
            ["The Replicator", 1.1],
            ["The Zealot's Amulet", 1.1],
            ["Tin of Fruitcake", 1.1],
            ["Tortured Root", 1.1],
            ["Toxic Focusing Crystal", 1.1],
            ["Toxic Maintenance Oil", 1.1],
            ["Toxic Sharpening Stone", 1.1],
            ["Triktiki Omelet", 1.1],
            ["Tropical Peppermint Cake", 1.1],
            ["Tuning Crystal Station", 1.1],
            ["Tuning Icicle", 1.1],
            ["Turnip Casserole", 1.1],
            ["Vallog's Demise", 1.1],
            ["Veggie Burger", 1.1],
            ["Veggie Pizza", 1.1],
            ["Vial of Maize Balm", 1.1],
            ["Whitefish Sushi", 1.1],
            ["Winterberry Pie", 1.1],
            ["Winterberry Sorbet", 1.1],
            ["Yam Fritter", 1.1],

            
            ["Roasted Parsnip", 1.05],
            ["Roasted Rutabaga", 1],
            ["Saffron Stuffed Mushroom", 1.27],
            ["Spinach Burger", 1],
            ["Spicier Flank Steak", 1.1],
            ["Stuffed Zucchini", 1],
            ["Sushi", 1.37],
            ["Zephyrite Fish Jerky", 1],

            // DUNGEON STUFF
            // ["Alpha Conduit", 75],
            // ["Ashes of the Effigy", 75],
            // ["Bloodstone Fragment", 75],
            // ["Claw of the Howling King", 75],
            // ["Colossus Fang", 75],
            // ["Eternal Flame (trinket)", 75],
            // ["Husk of the Destroyer", 75],
            // ["Infinity Loop", 75],
            // ["Koda's Gift", 75],
            // ["Nightmare Coil", 75],
            // ["Operative's Creed", 75],
            // ["Plague (ring)", 75],

            // ARTIFCER
            
        ];

        $restrictedItems = [
            "Recipe:",
            "Bowl of Red Meat Stock",
            "Bowl of Salsa",
            "Bowl of Vegetable Stock",
            "Cup of Potato Fries",
            "Hamburger",
            "Cheeseburger",
            "Dragon's Breath Bun",
            "Dragonfish Candy",
            "Dragonfly Cupcake",
            "Koi Cake",
            "Kralkachocolate Bar",
            "Fried Golden Dumpling",
            "Steamed Red Dumpling",
            "Spring Roll",
            "Sweet Bean Bun",
            "Bowl of Carne Khan Chili",
            "Bowl of Firebreather Chili",
            "Bowl of Green Chili Ice Cream",
            "Cup of Light-Roasted Coffee",
            "Omnomberry Compote",
            "Plate of Beef Rendang",
            "Bowl of Poultry Satay",
            "Quiche of Darkness Vegetable Mix",
            "Side of Charred Meat",
            "Trickster's Cream Pie",
            "Avocado Smoothie",
            "Loaf of Raspberry Peach Bread",
            "Loaf of Tarragon Bread",
            "Raspberry Peach Compote",
            "Raspberry Passion Fruit Compote",
            "Loaf of Rosemary Bread",
            "Longevity Noodles",
            "Unidentified Purple Dye",
            "White Cake",
            "Bowl of Strawberry Apple Compote",
            "Fried Banana Chips",
            "Ball of Cookie Dough",
            "Bowl of Blueberry Pie Filling",
            "Bowl of Candy Corn Custard",
            "Bowl of Chocolate Chip Ice Cream",
            "Bowl of Simple Poultry Soup",
            "Bowl ofSimple Stirfry",
            "Bowl of Staple Soup Vegetables",
            "Candied Apple",
            "Caramel Apple",
            "Chili Pepper Popper",
            "Drottot's Poached Egg",
            "Loaf of Bread",
            "Pasta Noodles",
            "Roasted Meaty Sandwich",
            "Spicy Meat Kabob",
            "Bowl of Sage Stuffing",
            "Bowl of Blackberry Pie Filling",
            "Bowl of Tangy Sautee Mix",
            "Bowl of Strawberry Pie Filling",
            "Bowl of Chocolate Raspberry Frosting",
            "Bowl of Winter Vegetable Mix",
            "Bowl of Pesto",
            "Bowl of Chocolate Cherry Frosting",
            "Bowl of Mango Pie Filling",
            "Bowl of Cherry Pie Filling",
            "Bowl of Orange Coconut Frosting",
            "Bowl of Chocolate Omnomberry Frosting",
            "Bowl of Grape Pie Filling",
            "Bowl of Simple Salad",
            "Bowl of Dolyak Stew",
            "Bowl of Simple Vegetable Soup",
            "Bowl of Green Bean Stew",
            "Bowl of Blueberry apple Compote",
            "Bowl of Simple Meat Chili",
            "Bowl of Sauteed Carrots",
            "Bowl of Simple Meat Stew",
            "Bowl of Poultry Noodle Soup",
            "Bowl of Simple Stirfry",
            "Bowl of Basic Vegetable Soup",
            "Bowl of Baker's Dry Ingredients",
            "Bowl of White Frosting",
            "Bowl of Omnomberry Pie Filling",
            "Bowl of Watery Mushroom Soup",
            "Bowl of Chocolate Frosting",
            "Bowl of Eztlitl Stuffing",
            "Bowl of Gelatinous Ooze Custard",
            "Bowl of Stirfry Base",
            "Bowl of Blackberry Pear Compote",
            "Bowl of Basic Poultry Soup",
            "Feast of Yam Fritters",
            "Honed Warband Visor",
            "Berserker's Legion Visor",
            "Berserker's Dreadnought Visor",
        ];

        $salvageableItemNames = array_column($salvageableItemCategories, 0); 
        $salvageableMap = array_column($salvageableItemCategories, 1, 0);
        $researchNotesResponse = [];

        $recipeController = new RecipeController();

        Items::where(function ($goodItemQuery) use ($salvageableItemNames){
            foreach ($salvageableItemNames as $name){
                $goodItemQuery->orWhere('name', 'like', '%'.$name.'%');
            }
        })
        ->where('level', '!=', 0)
        ->where('vendor_value', '!=', 0)
        ->where('type', '!=', 'CraftingMaterial')
        ->where(function ($badItemQuery) use ($restrictedItems){
            foreach ($restrictedItems as $restricted){
                $badItemQuery->where('name', 'not like', $restricted);
            }
        })
        ->chunk(100, function ($salvageableItems) use ($salvageableMap, $recipeController){
            foreach ($salvageableItems as $item){
                $recipe = Recipes::where('output_item_id', $item->id)->first();

                // Check if recipe is !null
                if ($recipe) {
                    // Reset avgOutput
                    $avgOutput = null; 
                    // Go through salvageableMap with the categories and their avgOutput
                    foreach ($salvageableMap as $category => $value){
                        // If the item name string matches one of the words in the $category
                        // Or if item name matches the $category exactly
                        if (strpos($item->name, $category) != false || $item->name == $category){
                            $avgOutput = $value; 
                            break;
                        }
                    }
                    if ($avgOutput){
                        ResearchNotes::updateOrCreate(
                            [
                                'recipe_id' => $recipe->id,
                                'item_id' => $item->id,
                            ],
                            [
                                'avg_output' => $avgOutput, // Use avg_output from map
                                'ingredients' => $recipe->ingredients,
                            ]  
                        );
                    }
                    
                }
            }
        });
    }
}
