<?php

namespace App\Jobs\Fetches;

use App\Models\Items;
use App\Models\Recipes;
use App\Models\ResearchNotes;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class FetchResearchNotes implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $salvageableItemCategories = [
            ["Draconic", 5.5],
            ["Tempered Scale", 6],
            ["Barbaric", 5.5],
            ["Splint", 5],
            ["Major Sigil", 1],
            ["Superior Sigil", 1],
            ["Nadijeh's", 275],
            ["Zehtuka's", 213],
            ["Wupwup", 275],
            ["Powerful Potion", 1],
            ["Potent Potion", 1],
            ["Strong Potion", 1],
            ["Minor Potion", 1],
            ["Soro's", 245],
            ["Grizzlemouth's", 245],
            ["Zintl", 240],
            ["Pearl", 45],
            ["Bottle of Batwing Brew", 1],
            ["Tuning Crystal", 1],
            ["Green Wood Scepter", 1],
            ["Irradiated Focus", 1],
            ["Harpy Totem", 1],
            ["Togo's", 240],
            ["Tengu Echo", 50],
            ["Astral", 50],
            ["Peppermint Oil", 1.03],
            ["Restored Boreal", 40],
            ["Mordant", 45],
            ["Elder Wood Warhorn", 5.83],
            ["Quality Maintenance Oil", 1.1],
            ["Hard Wood Warhorn", 6],
            ["Artisan Maintenance Oil", 1],
            ["Seasoned Wood Warhorn", 5],
            ["Soft Wood Short Bow", 3.14],
            ["Journeyman Maintenance Oil", 1.04],
            ["Bronze Rifle", 1],
            ["Orichalcum Earring", 83.33],
            ["Mithril Earring", 5],
            ["Mithril Amulet", 4],
            ["Mithril Ring", 5],
            ["Platinum Amulet", 3],
            ["Platinum Earring", 4],
            ["Platinum Ring", 4],
            ["Gold Band", 5],
            ["Gold Earring", 3.29],
            ["Gold Amulet", 3],
            ["Gold Ring", 3],
            ["Silver Earring", 2.17],
            ["Silver Ring", 3],
            ["Silver Pendant", 3],
            ["Silver Stud", 2.22],
            ["Copper Stud", 1],
            ["Copper Earring", 1],
            ["Copper Amulet", 1],
            ["Copper Ring", 1],
            ["The Twins'", 467],
            ["Togo's", 450],
            ["Ferratus's", 475],
            ["Emblazoned", 75],
            ["Lunatic Noble", 75],
            ["Prowler", 5],
            ["Noble", 5.36],
            ["Outlaw Mask", 3.2],
            ["Outlaw Shoulders", 3.2],
            ["Outlaw Coat", 3.2],
            ["Outlaw Gloves", 3.2],
            ["Outlaw Pants", 3.2],
            ["Outlaw Boots", 3.2],
            ["Seeker Shoulders", 1],
            ["Seeker Coat", 1],
            ["Seeker Gloves", 1],
            ["Seeker Pants", 1],
            ["Seeker Boots", 1],
            ["Jade Tech Masque", 75],
            ["Jade Tech Shoulderpads", 75],
            ["Jade Tech Vest", 75],
            ["Jade Tech Gloves", 75],
            ["Jade Tech Skirt", 75],
            ["Jade Tech Boots", 75],
            ["Exalted Masque", 75],
            ["Exalted Mantle", 75],
            ["Exalted Coat", 75],
            ["Exalted Gloves", 75],
            ["Exalted Pants", 75],
            ["Exalted Boots", 75],
            ["Stellar", 245],
            ["Zojja's", 345],
            ["Mathilde's", 250],
            ["Sharpening Skull", 1.12],
            ["Krait Slayer", 6],
            ["Krait Pilum", 5.12],
            ["Darksteel Dagger", 6.14],
            ["Darksteel Axe", 6.26],
            ["Beaded", 7],
            ["Dredge Spear", 4.98],
            ["Bronze Axe", 1],
            ["Bronze Sword", 1],
            ["Bronze Mace", 1],
            ["Bronze Spear", 1],
            ["Adventurer's Mantle", 6],
            // ASCENDED ARMOR
            ["Ahamid's Visor", 500],
            ["Ahamid's Pauldrons", 500],
            ["Ahamid's Breastplate", 300],
            ["Ahamid's Warfists", 500],
            ["Ahamid's Tassets", 500],
            ["Ahamid's Greaves", 500],
            ["Ahamid's Visage", 500],
            ["Ahamid's Shoulderguard", 500],
            ["Ahamid's Doublet", 300],
            ["Ahamid's Grips", 500],
            ["Ahamid's Leggings", 500],
            ["Ahamid's Striders", 500],
            ["Ahamid's Masque", 500],
            ["Ahamid's Epaulets", 500],
            ["Ahamid's Doublet", 300],
            ["Ahamid's Wristguards", 500],
            ["Ahamid's Breeches", 500],
            ["Ahamid's Footwear", 500],
            ["Angchu Helm", 500],
            ["Angchu Shoulders", 500],
            ["Angchu Chestplate", 300],
            ["Angchu Gauntlets", 500],
            ["Angchu Legguards", 500],
            ["Angchu Boots", 500],
            ["Angchu Visage", 500],
            ["Angchu Shoulderguard", 500],
            ["Angchu Doublet", 300],
            ["Angchu Grips", 500],
            ["Angchu Leggings", 500],
            ["Angchu Striders", 500],
            ["Angchu Masque", 500],
            ["Angchu Epaulets", 500],
            ["Angchu Doublet", 300],
            ["Angchu Wristguards", 500],
            ["Angchu Breeches", 500],
            ["Angchu Footwear", 500],
            ["Beigarth's Helm", 500],
            ["Beigarth's Shoulders", 500],
            ["Beigarth's Chestplate", 300],
            ["Beigarth's Gauntlets", 500],
            ["Beigarth's Legguards", 500],
            ["Beigarth's Boots", 500],
            ["Beigarth's Visage", 500],
            ["Beigarth's Shoulderguard", 500],
            ["Beigarth's Doublet", 300],
            ["Beigarth's Grips", 500],
            ["Beigarth's Leggings", 500],
            ["Beigarth's Striders", 500],
            ["Beigarth's Masque", 500],
            ["Beigarth's Epaulets", 500],
            ["Beigarth's Doublet", 300],
            ["Beigarth's Wristguards", 500],
            ["Beigarth's Breeches", 500],
            ["Beigarth's Footwear", 500],
            ["Ferratus's Helm", 500],
            ["Ferratus's Shoulders", 500],
            ["Ferratus's Chestplate", 300],
            ["Ferratus's Gauntlets", 500],
            ["Ferratus's Legguards", 500],
            ["Ferratus's Boots", 500],
            ["Ferratus's Visage", 500],
            ["Ferratus's Shoulderguard", 500],
            ["Ferratus's Doublet", 300],
            ["Ferratus's Grips", 500],
            ["Ferratus's Leggings", 500],
            ["Ferratus's Striders", 500],
            ["Ferratus's Masque", 500],
            ["Ferratus's Epaulets", 500],
            ["Ferratus's Doublet", 300],
            ["Ferratus's Wristguards", 500],
            ["Ferratus's Breeches", 500],
            ["Ferratus's Footwear", 500],
            ["Forgemaster's Helm", 500],
            ["Forgemaster's Shoulders", 500],
            ["Forgemaster's Chestplate", 300],
            ["Forgemaster's Gauntlets", 500],
            ["Forgemaster's Legguards", 500],
            ["Forgemaster's Boots", 500],
            ["Forgemaster's Visage", 500],
            ["Forgemaster's Shoulderguard", 500],
            ["Forgemaster's Doublet", 300],
            ["Forgemaster's Grips", 500],
            ["Forgemaster's Leggings", 500],
            ["Forgemaster's Striders", 500],
            ["Forgemaster's Masque", 500],
            ["Forgemaster's Epaulets", 500],
            ["Forgemaster's Doublet", 300],
            ["Forgemaster's Wristguards", 500],
            ["Forgemaster's Breeches", 500],
            ["Forgemaster's Footwear", 500],
            ["Gobrech's Helm", 500],
            ["Gobrech's Shoulders", 500],
            ["Gobrech's Chestplate", 300],
            ["Gobrech's Gauntlets", 500],
            ["Gobrech's Legguards", 500],
            ["Gobrech's Boots", 500],
            ["Gobrech's Visage", 500],
            ["Gobrech's Shoulderguard", 500],
            ["Gobrech's Doublet", 300],
            ["Gobrech's Grips", 500],
            ["Gobrech's Leggings", 500],
            ["Gobrech's Striders", 500],
            ["Gobrech's Masque", 500],
            ["Gobrech's Epaulets", 500],
            ["Gobrech's Doublet", 300],
            ["Gobrech's Wristguards", 500],
            ["Gobrech's Breeches", 500],
            ["Gobrech's Footwear", 500],
            ["Hronk's Helm", 500],
            ["Hronk's Shoulders", 500],
            ["Hronk's Chestplate", 300],
            ["Hronk's Gauntlets", 500],
            ["Hronk's Legguards", 500],
            ["Hronk's Boots", 500],
            ["Hronk's Visage", 500],
            ["Hronk's Shoulderguard", 500],
            ["Hronk's Doublet", 300],
            ["Hronk's Grips", 500],
            ["Hronk's Leggings", 500],
            ["Hronk's Striders", 500],
            ["Hronk's Masque", 500],
            ["Hronk's Epaulets", 500],
            ["Hronk's Doublet", 300],
            ["Hronk's Wristguards", 500],
            ["Hronk's Breeches", 500],
            ["Hronk's Footwear", 500],
            ["Leftpaw's Helm", 500],
            ["Leftpaw's Shoulders", 500],
            ["Leftpaw's Chestplate", 300],
            ["Leftpaw's Gauntlets", 500],
            ["Leftpaw's Legguards", 500],
            ["Leftpaw's Boots", 500],
            ["Leftpaw's Visage", 500],
            ["Leftpaw's Shoulderguard", 500],
            ["Leftpaw's Doublet", 300],
            ["Leftpaw's Grips", 500],
            ["Leftpaw's Leggings", 500],
            ["Leftpaw's Striders", 500],
            ["Leftpaw's Masque", 500],
            ["Leftpaw's Epaulets", 500],
            ["Leftpaw's Doublet", 300],
            ["Leftpaw's Wristguards", 500],
            ["Leftpaw's Breeches", 500],
            ["Leftpaw's Footwear", 500],
            ["Morbach's Helm", 500],
            ["Morbach's Shoulders", 500],
            ["Morbach's Chestplate", 300],
            ["Morbach's Gauntlets", 500],
            ["Morbach's Legguards", 500],
            ["Morbach's Boots", 500],
            ["Morbach's Visage", 500],
            ["Morbach's Shoulderguard", 500],
            ["Morbach's Doublet", 300],
            ["Morbach's Grips", 500],
            ["Morbach's Leggings", 500],
            ["Morbach's Striders", 500],
            ["Morbach's Masque", 500],
            ["Morbach's Epaulets", 500],
            ["Morbach's Doublet", 300],
            ["Morbach's Wristguards", 500],
            ["Morbach's Breeches", 500],
            ["Morbach's Footwear", 500],
            ["Occam's Helm", 500],
            ["Occam's Shoulders", 500],
            ["Occam's Chestplate", 300],
            ["Occam's Gauntlets", 500],
            ["Occam's Legguards", 500],
            ["Occam's Boots", 500],
            ["Occam's Visage", 500],
            ["Occam's Shoulderguard", 500],
            ["Occam's Doublet", 300],
            ["Occam's Grips", 500],
            ["Occam's Leggings", 500],
            ["Occam's Striders", 500],
            ["Occam's Masque", 500],
            ["Occam's Epaulets", 500],
            ["Occam's Doublet", 300],
            ["Occam's Wristguards", 500],
            ["Occam's Breeches", 500],
            ["Occam's Footwear", 500],
            ["Saphir's Helm", 500],
            ["Saphir's Shoulders", 500],
            ["Saphir's Chestplate", 300],
            ["Saphir's Gauntlets", 500],
            ["Saphir's Legguards", 500],
            ["Saphir's Boots", 500],
            ["Saphir's Visage", 500],
            ["Saphir's Shoulderguard", 500],
            ["Saphir's Doublet", 300],
            ["Saphir's Grips", 500],
            ["Saphir's Leggings", 500],
            ["Saphir's Striders", 500],
            ["Saphir's Masque", 500],
            ["Saphir's Epaulets", 500],
            ["Saphir's Doublet", 300],
            ["Saphir's Wristguards", 500],
            ["Saphir's Breeches", 500],
            ["Saphir's Footwear", 500],
            ["Tateos's Helm", 500],
            ["Tateos's Shoulders", 500],
            ["Tateos's Chestplate", 300],
            ["Tateos's Gauntlets", 500],
            ["Tateos's Legguards", 500],
            ["Tateos's Boots", 500],
            ["Tateos's Visage", 500],
            ["Tateos's Shoulderguard", 500],
            ["Tateos's Doublet", 300],
            ["Tateos's Grips", 500],
            ["Tateos's Leggings", 500],
            ["Tateos's Striders", 500],
            ["Tateos's Masque", 500],
            ["Tateos's Epaulets", 500],
            ["Tateos's Doublet", 300],
            ["Tateos's Wristguards", 500],
            ["Tateos's Breeches", 500],
            ["Tateos's Footwear", 500],
            ["Veldrunner Helm", 500],
            ["Veldrunner Shoulders", 500],
            ["Veldrunner Chestplate", 300],
            ["Veldrunner Gauntlets", 500],
            ["Veldrunner Legguards", 500],
            ["Veldrunner Boots", 500],
            ["Veldrunner Visage", 500],
            ["Veldrunner Shoulderguard", 500],
            ["Veldrunner Doublet", 300],
            ["Veldrunner Grips", 500],
            ["Veldrunner Leggings", 500],
            ["Veldrunner Striders", 500],
            ["Veldrunner Masque", 500],
            ["Veldrunner Epaulets", 500],
            ["Veldrunner Doublet", 300],
            ["Veldrunner Wristguards", 500],
            ["Veldrunner Breeches", 500],
            ["Veldrunner Footwear", 500],
            ["Wei Qi's Helm", 500],
            ["Wei Qi's Shoulders", 500],
            ["Wei Qi's Chestplate", 300],
            ["Wei Qi's Gauntlets", 500],
            ["Wei Qi's Legguards", 500],
            ["Wei Qi's Boots", 500],
            ["Wei Qi's Visage", 500],
            ["Wei Qi's Shoulderguard", 500],
            ["Wei Qi's Doublet", 300],
            ["Wei Qi's Grips", 500],
            ["Wei Qi's Leggings", 500],
            ["Wei Qi's Striders", 500],
            ["Wei Qi's Masque", 500],
            ["Wei Qi's Epaulets", 500],
            ["Wei Qi's Doublet", 300],
            ["Wei Qi's Wristguards", 500],
            ["Wei Qi's Breeches", 500],
            ["Wei Qi's Footwear", 500],
            ["Wupwup Helm", 500],
            ["Wupwup Shoulders", 500],
            ["Wupwup Chestplate", 300],
            ["Wupwup Gauntlets", 500],
            ["Wupwup Legguards", 500],
            ["Wupwup Boots", 500],
            ["Wupwup Visage", 500],
            ["Wupwup Shoulderguard", 500],
            ["Wupwup Doublet", 300],
            ["Wupwup Grips", 500],
            ["Wupwup Leggings", 500],
            ["Wupwup Striders", 500],
            ["Wupwup Masque", 500],
            ["Wupwup Epaulets", 500],
            ["Wupwup Doublet", 300],
            ["Wupwup Wristguards", 500],
            ["Wupwup Breeches", 500],
            ["Wupwup Footwear", 500],
            ["Zintl Helm", 500],
            ["Zintl Shoulders", 500],
            ["Zintl Chestplate", 300],
            ["Zintl Gauntlets", 500],
            ["Zintl Legguards", 500],
            ["Zintl Boots", 500],
            ["Zintl Visage", 500],
            ["Zintl Shoulderguard", 500],
            ["Zintl Doublet", 300],
            ["Zintl Grips", 500],
            ["Zintl Leggings", 500],
            ["Zintl Striders", 500],
            ["Zintl Masque", 500],
            ["Zintl Epaulets", 500],
            ["Zintl Doublet", 300],
            ["Zintl Wristguards", 500],
            ["Zintl Breeches", 500],
            ["Zintl Footwear", 500],
            ["Zojja's Helm", 500],
            ["Zojja's Shoulders", 500],
            ["Zojja's Chestplate", 300],
            ["Zojja's Gauntlets", 500],
            ["Zojja's Legguards", 500],
            ["Zojja's Boots", 500],
            ["Zojja's Visage", 500],
            ["Zojja's Shoulderguard", 500],
            ["Zojja's Doublet", 300],
            ["Zojja's Grips", 500],
            ["Zojja's Leggings", 500],
            ["Zojja's Striders", 500],
            ["Zojja's Masque", 500],
            ["Zojja's Epaulets", 500],
            ["Zojja's Doublet", 300],
            ["Zojja's Wristguards", 500],
            ["Zojja's Breeches", 500],
            ["Zojja's Footwear", 500],
            
            // OTHER ARMOR
            ["Amnemoi's Robe", 7.5],
            ["Anointed Diadem", 7.5],
            ["Barca's", 3.5],
            ["Bella's", 13],
            ["Blessed Steps", 13],
            ["Bloodsaw Leather", 3.7],
            ["Breezy Backplate", 13],
            ["Brightcarved", 5.6],
            ["Cabras", 3.4],
            ["Clarion", 7],
            ["Clark's Chukkas", 13],
            ["Cloven", 3.7],
            ["Cumulus Habit", 8],
            ["Darkvine", 1.1],

            // CHEF
            ["Tuning Icicle", 1.08],
            ["Lump of Crystallized Nougat", 1],
            ["Bowl of", 1.3],
            ["Cup of", 1.3],
            ["Saffron Stuffed Mushroom", 1.27],
            ["Flatbread", 1.38],
            ["Loaf of", 1.3],
            ["Chocolate Raspberry Cream", 1.13],
            ["Roasted Parsnip", 1.05],
            ["Spicier Flank Steak", 1.1],
            ["Griffon Egg Omelet", 1],
            ["Roasted Rutabaga", 1],
            ["Plate of", 1],
            ["Sushi", 1.37],
            ["Eztlitl Stuffed Mushroom", 1],
            ["Filet of", 1],
            ["Piece of Candy Corn Almond Brittle", 1],
            ["Grape Pie", 1],
            ["Stuffed Zucchini", 1],
            ["Cherry Pie", 1],
            ["Triktiki Omelet", 1],
            ["Yam Fritter", 1],
            ["Spinach Burger", 1],
            ["Zephyrite Fish Jerky", 1],
            ["Feathered", 5.5],
            ["Block of Tofu", 1.1],
        ];

        $restrictedItems = [
            "Recipe:",
            "Bowl of Red Meat Stock",
            "Bowl of Salsa",
            "Bowl of Vegetable Stock",
            "Cup of Potato Fries",
            "Hamburger",
            "Cheeseburger",
            "Dragon's Breath Bun",
            "Dragonfish Candy",
            "Dragonfly Cupcake",
            "Koi Cake",
            "Kralkachocolate Bar",
            "Fried Golden Dumpling",
            "Steamed Red Dumpling",
            "Spring Roll",
            "Sweet Bean Bun",
            "Bowl of Carne Khan Chili",
            "Bowl of Firebreather Chili",
            "Bowl of Green Chili Ice Cream",
            "Cup of Light-Roasted Coffee",
            "Omnomberry Compote",
            "Plate of Beef Rendang",
            "Bowl of Poultry Satay",
            "Quiche of Darkness Vegetable Mix",
            "Side of Charred Meat",
            "Trickster's Cream Pie",
            "Avocado Smoothie",
            "Loaf of Raspberry Peach Bread",
            "Loaf of Tarragon Bread",
            "Raspberry Peach Compote",
            "Raspberry Passion Fruit Compote",
            "Loaf of Rosemary Bread",
            "Longevity Noodles",
            "Unidentified Purple Dye",
            "White Cake",
            "Bowl of Strawberry Apple Compote",
            "Fried Banana Chips",
            "Ball of Cookie Dough",
            "Bowl of Blueberry Pie Filling",
            "Bowl of Candy Corn Custard",
            "Bowl of Chocolate Chip Ice Cream",
            "Bowl of Simple Poultry Soup",
            "Bowl ofSimple Stirfry",
            "Bowl of Staple Soup Vegetables",
            "Candied Apple",
            "Caramel Apple",
            "Chili Pepper Popper",
            "Drottot's Poached Egg",
            "Loaf of Bread",
            "Pasta Noodles",
            "Roasted Meaty Sandwich",
            "Spicy Meat Kabob",
            "Bowl of Sage Stuffing",
            "Bowl of Blackberry Pie Filling",
            "Bowl of Tangy Sautee Mix",
            "Bowl of Strawberry Pie Filling",
            "Bowl of Chocolate Raspberry Frosting",
            "Bowl of Winter Vegetable Mix",
            "Bowl of Pesto",
            "Bowl of Chocolate Cherry Frosting",
            "Bowl of Mango Pie Filling",
            "Bowl of Cherry Pie Filling",
            "Bowl of Orange Coconut Frosting",
            "Bowl of Chocolate Omnomberry Frosting",
            "Bowl of Grape Pie Filling",
            "Bowl of Simple Salad",
            "Bowl of Dolyak Stew",
            "Bowl of Simple Vegetable Soup",
            "Bowl of Green Bean Stew",
            "Bowl of Blueberry apple Compote",
            "Bowl of Simple Meat Chili",
            "Bowl of Sauteed Carrots",
            "Bowl of Simple Meat Stew",
            "Bowl of Poultry Noodle Soup",
            "Bowl of Simple Stirfry",
            "Bowl of Basic Vegetable Soup",
            "Bowl of Baker's Dry Ingredients",
            "Bowl of White Frosting",
            "Bowl of Omnomberry Pie Filling",
            "Bowl of Watery Mushroom Soup",
            "Bowl of Chocolate Frosting",
            "Bowl of Eztlitl Stuffing",
            "Bowl of Gelatinous Ooze Custard",
            "Bowl of Stirfry Base",
            "Bowl of Blackberry Pear Compote",
            "Bowl of Basic Poultry Soup",
            "Feast of Yam Fritters",
            "Honed Warband Visor",
            "Berserker's Legion Visor",
            "Berserker's Dreadnought Visor",
        ];

        $salvageableItemNames = array_column($salvageableItemCategories, 0); 
        $salvageableMap = array_column($salvageableItemCategories, 1, 0);
        $researchNotesResponse = [];

        Items::where(function ($goodItemQuery) use ($salvageableItemNames){
            foreach ($salvageableItemNames as $name){
                $goodItemQuery->orWhere('name', 'like', '%'.$name.'%');
            }
        })
        ->where('level', '!=', 0)
        ->where('vendor_value', '!=', 0)
        ->where('type', '!=', 'CraftingMaterial')
        ->where(function ($badItemQuery) use ($restrictedItems){
            foreach ($restrictedItems as $restricted){
                $badItemQuery->where('name', 'not like', $restricted);
            }
        })
        ->chunk(100, function ($salvageableItems) use ($salvageableMap){
            foreach ($salvageableItems as $item){
                $recipe = Recipes::where('output_item_id', $item->id)->first();

                // Check if recipe is !null
                if ($recipe) {
                    // Reset avgOutput
                    $avgOutput = null; 
                    // Go through salvageableMap with the categories and their avgOutput
                    foreach ($salvageableMap as $category => $value){
                        // If the item name string matches one of the words in the $category
                        // Or if item name matches the $category exactly
                        if (strpos($item->name, $category) != false || $item->name == $category){
                            $avgOutput = $value; 
                            break;
                        }
                    }
                    if ($avgOutput){
                        ResearchNotes::updateOrCreate(
                            [
                                'recipe_id' => $recipe->id,
                                'item_id' => $item->id,
                            ],
                            [
                                'avg_output' => $avgOutput, // Use avg_output from map
                                'ingredients' => $recipe->ingredients,
                            ]  
                        );
                    }
                    
                }
            }
        });
    }
}
